spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: user_schema
  cache:
    type: redis
    redis:
      time-to-live: 30m
  flyway:
    table: flyway_schema_history_user
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
  session:
    store-type: redis
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
security:
  oauth2:
    client:
      client-id: user-service-client
      client-secret: 1e279f48-7995-11ea-bc55-0242ac130003
      grant-type: client_credentials
      access-token-uri: http://localhost/oauth/token
      scope: any
    resource:
      token-info-uri: http://localhost/oauth/check_token

management:
  endpoints:
    web:
      base-path: /api/v1/users/actuator

xroad:
  security-server: http://195.20.151.53:10080
  id-code: 45307316010
  client:
    instance: ee-dev
    member-class: GOV
    member-code: 70006317
    subsystem-code: riigiportaal-citizen
  rr:
    protocol-version: 4.0
    instance: ee-dev
    member-class: GOV
    member-code: 70008440
    subsystem-code: rr
  aar:
    protocol-version: 4.0
    instance: ee-dev
    member-class: GOV
    member-code: 70006317
    subsystem-code: aar

logging:
  level:
    root: info
    tech.introduct: debug
