FROM python:3.7

RUN apt-get update
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
RUN apt-get install -y software-properties-common

RUN apt-get install -y default-jre
RUN curl -o allure-2.7.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.7.0/allure-2.7.0.tgz && \
 tar -zxvf allure-2.7.0.tgz -C /opt/ && \
 ln -s /opt/allure-2.7.0/bin/allure /usr/bin/allure && \
 allure --version

RUN mkdir /root/.selene/
WORKDIR /app
RUN mkdir /app/public/

COPY . .

ENV PATH=${PATH}:/root/.poetry/bin
RUN poetry install
